baseURL = "https://hefailed.com/"
publishDir = "docs"
languageCode = "en-us"
title = "He Failed"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 8
enableGitInfo = true

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/headroom/headroom.js"
  [[params.plugins.js]]
  URL = "plugins/instafeed/instafeed.min.js"
  [[params.plugins.js]]
  URL = "plugins/masonry/masonry.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/smooth-scroll/smooth-scroll.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  
# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3


[params]
# Link custom assets relative to /static
logo = "img/mbs-djt-bff-1400x200.jpg"
home = "Home"
# hompage layout ( two layout is available,  you can set the another layout by change the value of homeLayoutToggle "true" to "false")
homeLayoutToggle = true
# Meta data
description = "MAKE ARYANS GO APESHIT"
# about author
author = "Failure Inspector General"
authorImage = "img/stable-genius.jpg"
shortDescription = "The US President doesn't want a United States. He prefers a cold civil war."
# Contact Form Action
contactFormAction = "#"
# Google Analitycs
googleAnalitycsID = ""
# copyright
copyright = "Driven by megalomania since 1946."

  # Preloader
  [params.preloader]
  enable = true
  
  # search
  [params.search]
  enable = false

  # Instagram feed
  [params.instafeed]
  enable = false
  userID = ""
  accessToken = ""

  # footer
  [params.footer]

    #address
    [[params.footer.addresses]]
    address = "America"
    
    [[params.footer.addresses]]
    address = "United States"

    
    #contact information
    [[params.footer.contacts]]
    contactInfo = ""
    
    [[params.footer.contacts]]
    contactInfo = ""


  # social site
  [[params.social]]
  icon = "ti-facebook"
  URL = "#"
  
  [[params.social]]
  icon = "ti-twitter-alt"
  URL = "#"
  
  [[params.social]]
  icon = "ti-linkedin"
  URL = "#"
  
  [[params.social]]
  icon = "ti-github"
  URL = "#"